In [1]:
import cv2

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np
import time

In [4]:
def main():
    imgpath1="C:\\Users\\user\\Downloads\\opencv\\misc\\house.tiff"
    
    img1=cv2.imread(imgpath1,1)
    img1=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
    
    rows,columns,channels=img1.shape
    
    angle=0
    
    while True:
        if  angle==360:
            angle=o
            
        R=cv2.getRotationMatrix2D((columns/2,rows/2),angle,1)
        
    
    
        print(R)
    
    
        output=cv2.warpAffine(img1,R,(columns,rows))
    
        cv2.imshow('ROTATED IMAGE',output)
        angle=angle+1
        time.sleep(0.01)
        
        if cv2.waitKey(1)==27:
            break
            
    cv2.destroyWindow('ROTATED IMAGE')        
        
   
    
if __name__=="__main__":
    main()

[[ 1.  0.  0.]
 [-0.  1.  0.]]
[[ 0.9998477   0.01745241 -4.42882601]
 [-0.01745241  0.9998477   4.50680609]]
[[ 0.99939083  0.0348995  -8.77832287]
 [-0.0348995   0.99939083  9.09021944]]
[[  0.99862953   0.05233596 -13.0471657 ]
 [ -0.05233596   0.99862953  13.7488439 ]]
[[  0.99756405   0.06975647 -17.23405415]
 [ -0.06975647   0.99756405  18.48126041]]
[[  0.9961947    0.08715574 -21.33771285]
 [ -0.08715574   0.9961947   23.28602743]]
[[  0.9945219    0.10452846 -25.35689181]
 [ -0.10452846   0.9945219   28.16168138]]
[[  0.99254615   0.12186934 -29.29036673]
 [ -0.12186934   0.99254615  33.10673709]]
[[  0.99026807   0.1391731  -33.13693944]
 [ -0.1391731    0.99026807  38.11968825]]
[[  0.98768834   0.15643447 -36.89543824]
 [ -0.15643447   0.98768834  43.19900786]]
[[  0.98480775   0.17364818 -40.56471825]
 [ -0.17364818   0.98480775  48.34314871]]
[[  0.98162718   0.190809   -44.14366178]
 [ -0.190809     0.98162718  53.55054385]]
[[  0.9781476    0.20791169 -47.63117864]
 [ -

[[-1.56434465e-01  9.87688341e-01  4.31990079e+01]
 [-9.87688341e-01 -1.56434465e-01  5.48895438e+02]]
[[-1.73648178e-01  9.84807753e-01  4.83431487e+01]
 [-9.84807753e-01 -1.73648178e-01  5.52564718e+02]]
[[-1.90808995e-01  9.81627183e-01  5.35505439e+01]
 [-9.81627183e-01 -1.90808995e-01  5.56143662e+02]]
[[-2.07911691e-01  9.78147601e-01  5.88196071e+01]
 [-9.78147601e-01 -2.07911691e-01  5.59631179e+02]]
[[-2.24951054e-01  9.74370065e-01  6.41487333e+01]
 [-9.74370065e-01 -2.24951054e-01  5.63026206e+02]]
[[-2.41921896e-01  9.70295726e-01  6.95362993e+01]
 [-9.70295726e-01 -2.41921896e-01  5.66327711e+02]]
[[-2.58819045e-01  9.65925826e-01  7.49806640e+01]
 [-9.65925826e-01 -2.58819045e-01  5.69534687e+02]]
[[-2.75637356e-01  9.61261696e-01  8.04801689e+01]
 [-9.61261696e-01 -2.75637356e-01  5.72646157e+02]]
[[-2.92371705e-01  9.56304756e-01  8.60331389e+01]
 [-9.56304756e-01 -2.92371705e-01  5.75661174e+02]]
[[-3.09016994e-01  9.51056516e-01  9.16378824e+01]
 [-9.51056516e-01 -3.0

[[-9.84807753e-01 -1.73648178e-01  5.52564718e+02]
 [ 1.73648178e-01 -9.84807753e-01  4.63656851e+02]]
[[-9.81627183e-01 -1.90808995e-01  5.56143662e+02]
 [ 1.90808995e-01 -9.81627183e-01  4.58449456e+02]]
[[-9.78147601e-01 -2.07911691e-01  5.59631179e+02]
 [ 2.07911691e-01 -9.78147601e-01  4.53180393e+02]]
[[-9.74370065e-01 -2.24951054e-01  5.63026206e+02]
 [ 2.24951054e-01 -9.74370065e-01  4.47851267e+02]]
[[-9.70295726e-01 -2.41921896e-01  5.66327711e+02]
 [ 2.41921896e-01 -9.70295726e-01  4.42463701e+02]]
[[-9.65925826e-01 -2.58819045e-01  5.69534687e+02]
 [ 2.58819045e-01 -9.65925826e-01  4.37019336e+02]]
[[-9.61261696e-01 -2.75637356e-01  5.72646157e+02]
 [ 2.75637356e-01 -9.61261696e-01  4.31519831e+02]]
[[-9.56304756e-01 -2.92371705e-01  5.75661174e+02]
 [ 2.92371705e-01 -9.56304756e-01  4.25966861e+02]]
[[-9.51056516e-01 -3.09016994e-01  5.78578819e+02]
 [ 3.09016994e-01 -9.51056516e-01  4.20362118e+02]]
[[-9.45518576e-01 -3.25568154e-01  5.81398203e+02]
 [ 3.25568154e-01 -9.4

[[ 1.56434465e-01 -9.87688341e-01  4.68800992e+02]
 [ 9.87688341e-01  1.56434465e-01 -3.68954382e+01]]
[[ 1.73648178e-01 -9.84807753e-01  4.63656851e+02]
 [ 9.84807753e-01  1.73648178e-01 -4.05647183e+01]]
[[ 1.90808995e-01 -9.81627183e-01  4.58449456e+02]
 [ 9.81627183e-01  1.90808995e-01 -4.41436618e+01]]
[[ 2.07911691e-01 -9.78147601e-01  4.53180393e+02]
 [ 9.78147601e-01  2.07911691e-01 -4.76311786e+01]]
[[ 2.24951054e-01 -9.74370065e-01  4.47851267e+02]
 [ 9.74370065e-01  2.24951054e-01 -5.10262065e+01]]
[[ 2.41921896e-01 -9.70295726e-01  4.42463701e+02]
 [ 9.70295726e-01  2.41921896e-01 -5.43277112e+01]]
[[ 2.58819045e-01 -9.65925826e-01  4.37019336e+02]
 [ 9.65925826e-01  2.58819045e-01 -5.75346871e+01]]
[[ 2.75637356e-01 -9.61261696e-01  4.31519831e+02]
 [ 9.61261696e-01  2.75637356e-01 -6.06461572e+01]]
[[ 2.92371705e-01 -9.56304756e-01  4.25966861e+02]
 [ 9.56304756e-01  2.92371705e-01 -6.36611739e+01]]
[[ 3.09016994e-01 -9.51056516e-01  4.20362118e+02]
 [ 9.51056516e-01  3.0

NameError: name 'o' is not defined